min_particles: 100
max_particles: 5000
kld_err: 0.01
kld_z: 0.99
# update_min_d: 0.05
# update_min_a: 0.2
update_min_d: -1
update_min_a: -1

resample_interval: 2
transform_tolerance: 0.1
recovery_alpha_slow: 0.00
recovery_alpha_fast: 0.00
initial_pose_x: 0
initial_pose_y: 0
initial_pose_a: 0
# initial_cov_xx: 0
# initial_cov_yy: 0
# initial_cov_aa: 0
gui_publish_rate: -1
save_pose_rate: 0.5
use_map_topic: false
first_map_only: false
selective_resampling: false
laser_min_range: -1
laser_max_range: -1
laser_max_beams: 30
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

odom_model_type: diff
odom_alpha1: 0.9
odom_alpha2: 0.5
odom_alpha3: 0.2
odom_alpha4: 0.5
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map
tf_broadcast: false

